version: '13'
services:
   react-project-dev:
      container_name: react_project_container
      image: react-docker
      build:
        context: .
        dockerfile: Dockerfile
      ports:
       - "3000:3000"
      volumes:
       - .:/app
       - /app/node_modules
      command: npm run start

  